### ISSUE TITLE
push update to npm

### ISSUE THREAD

**Issue by craig2017** [mewben/ember-cli-icheck#2]
Awesome ember plugin.  

Can you push the latest version to npm?  I'm getting errors on the a.each bug that you already fixed. 

https://www.npmjs.com/package/ember-cli-icheck

I was also wondering if you could add this too.  This just allows people to override your defaults from 

ember-cli-icheck/addon/components/i-check.js

```
var icheck = this.$().iCheck({
    checkboxClass: this.getWithDefault('checkboxClass', 'icheckbox_square-blue'),
    radioClass: this.getWithDefault('radioClass', 'iradio_square-blue'),
    increaseArea: this.getWithDefault('areaIncrease', '20%')
});
```

Thanks!

**Comment by mewben** [comment]
Thanks for the PR.. Sorry haven't had the time to update this...

**Comment by friscoMad** [comment]
Github is updated but not npm pls push whenever you can.
