### ISSUE TITLE
iCheck doesn't render

### ISSUE THREAD

**Issue by herzzanu** [mewben/ember-cli-icheck#4]
Using ember v 2.4.1, the iCheck component render as a regular checkbox. Can you test this on the latest Ember version and see if it works?

**Comment by meszike123** [comment]
Hi, I had the same problem (using Ember 2,4,2), but then I realized that the new 0.0.8 version is not in npm. 
So right now the workaround is to put the link to master repository in your package.json

```
"ember-cli-icheck": "https://github.com/mewben/ember-cli-icheck.git#master"
```

then it should work

**Comment by herzzanu** [comment]
Thank you for your help @meszike123 I didn't realize there's a newer version of it. I just updated the package.json and it works now.
